name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: scan-build ./configure
    - name: make clean
      run: scan-build --keep-cc make clean
    - name: make
      run: scan-build --keep-cc make

